// Generated by https://quicktype.io

export interface Movie {
  page:          number;
  results:       Result[];
  total_pages:   number;
  total_results: number;
}

export interface Result {
  adult:             boolean;
  backdrop_path:     string;
  genre_ids:         number[];
  id:                number;
  original_language: OriginalLanguage;
  original_title:    string;
  overview:          string;
  popularity:        number;
  poster_path:       string;
  release_date:      string;
  title:             string;
  video:             boolean;
  vote_average:      number;
  vote_count:        number;

  belongs_to_collection?: null;
  budget:                number;
  homepage?:              string;
  imdb_id?:               string;
  production_companies?:  ProductionCompany[];
  production_countries?:  ProductionCountry[];
  revenue?:               number;
  runtime?:               number;
  spoken_languages?:      SpokenLanguage[];
  status?:                string;
  tagline?:               string;
}

export enum OriginalLanguage {
  CN = "cn",
  En = "en",
  Hi = "hi",
}
export interface ProductionCompany {
  id:             number;
  logo_path:      null | string;
  name:           string;
  origin_country: string;
}

export interface ProductionCountry {
  iso_3166_1: string;
  name:       string;
}
export interface SpokenLanguage {
  english_name: string;
  iso_639_1:    string;
  name:         string;
}
